server:
  servlet:
    context-path: /book-reader
  port: 8080

spring:
  main:
    application-class: br.com.bookreader.application.BookReaderApplication
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/books_market_db?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC&useSSL=false
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  show-sql: true
  jackson:
    default-property-inclusion: non-null
